### PR TITLE
Add GitHub Actions workflow

### PR DESCRIPTION
**Pull request by nicolasbock**
Signed-off-by: Nicolas Bock <nicolas.bock@canonical.com>

### CODE REVIEW

**Comment by nicolasbock** [comment]
The workflow is not starting for some reason. I may not be privileged to start it? The result should be the same as

https://github.com/nicolasbock/charm-helpers/pull/2

**Review by ajkavanagh — APPROVED** [review]
LGTM

**Comment by ajkavanagh** [comment]
Do we want to remove travis at the same time in the PR?  (I say this, immediately after approving it!)

**Comment by ajkavanagh** [comment]
> I think that would make sense. Do you want me to add that to this PR? I'll remove the `.travis.yml` file.

Yes please!  Thanks.

**Comment by nicolasbock** [comment]
Done

**Review by ajkavanagh — APPROVED** [review]

**Pull request merged**
