### PR TITLE
SSL File writing should use byte mode

### LINKED ISSUE #57: stack trace when writing rabbit_ssl_ca to the neutron-api config
2017-11-18 11:04:41 DEBUG juju-log amqp:46: Generating template context for amqp
2017-11-18 11:04:41 DEBUG amqp-relation-changed Traceback (most recent call last):
2017-11-18 11:04:41 DEBUG amqp-relation-changed   File "/var/lib/juju/agents/unit-neutron-api-0/charm/hooks/amqp-relation-changed", line 732, in <module>
2017-11-18 11:04:41 DEBUG amqp-relation-changed     main()
2017-11-18 11:04:41 DEBUG amqp-relation-changed   File "/var/lib/juju/agents/unit-neutron-api-0/charm/hooks/amqp-relation-changed", line 725, in main
2017-11-18 11:04:41 DEBUG amqp-relation-changed     hooks.execute(sys.argv)
2017-11-18 11:04:41 DEBUG amqp-relation-changed   File "/var/lib/juju/agents/unit-neutron-api-0/charm/hooks/charmhelpers/core/hookenv.py", line 797, in execute
2017-11-18 11:04:41 DEBUG amqp-relation-changed     self._hooks[hook_name]()
2017-11-18 11:04:41 DEBUG amqp-relation-changed   File "/var/lib/juju/agents/unit-neutron-api-0/charm/hooks/charmhelpers/contrib/openstack/utils.py", line 1890, in wrapped_f
2017-11-18 11:04:41 DEBUG amqp-relation-changed     restart_functions)
2017-11-18 11:04:41 DEBUG amqp-relation-changed   File "/var/lib/juju/agents/unit-neutron-api-0/charm/hooks/charmhelpers/core/host.py", line 728, in restart_on_change_helper
2017-11-18 11:04:41 DEBUG amqp-relation-changed     r = lambda_f()
2017-11-18 11:04:41 DEBUG amqp-relation-changed   File "/var/lib/juju/agents/unit-neutron-api-0/charm/hooks/charmhelpers/contrib/openstack/utils.py", line 1889, in <lambda>
2017-11-18 11:04:41 DEBUG amqp-relation-changed     (lambda: f(*args, **kwargs)), restart_map, stopstart,
2017-11-18 11:04:41 DEBUG amqp-relation-changed   File "/var/lib/juju/agents/unit-neutron-api-0/charm/hooks/amqp-relation-changed", line 319, in amqp_changed
2017-11-18 11:04:41 DEBUG amqp-relation-changed     if 'amqp' not in CONFIGS.complete_contexts():
2017-11-18 11:04:41 DEBUG amqp-relation-changed   File "/var/lib/juju/agents/unit-neutron-api-0/charm/hooks/charmhelpers/contrib/openstack/templating.py", line 304, in complete_contexts
2017-11-18 11:04:41 DEBUG amqp-relation-changed     for i in six.itervalues(self.templates)]
2017-11-18 11:04:41 DEBUG amqp-relation-changed   File "/var/lib/juju/agents/unit-neutron-api-0/charm/hooks/charmhelpers/contrib/openstack/templating.py", line 304, in <listcomp>
2017-11-18 11:04:41 DEBUG amqp-relation-changed     for i in six.itervalues(self.templates)]
2017-11-18 11:04:41 DEBUG amqp-relation-changed   File "/var/lib/juju/agents/unit-neutron-api-0/charm/hooks/charmhelpers/contrib/openstack/templating.py", line 124, in complete_contexts
2017-11-18 11:04:41 DEBUG amqp-relation-changed     self.context()
2017-11-18 11:04:41 DEBUG amqp-relation-changed   File "/var/lib/juju/agents/unit-neutron-api-0/charm/hooks/charmhelpers/contrib/openstack/templating.py", line 109, in context
2017-11-18 11:04:41 DEBUG amqp-relation-changed     _ctxt = context()
2017-11-18 11:04:41 DEBUG amqp-relation-changed   File "/var/lib/juju/agents/unit-neutron-api-0/charm/hooks/neutron_api_context.py", line 708, in __call__
2017-11-18 11:04:41 DEBUG amqp-relation-changed     context = super(NeutronAMQPContext, self).__call__()
2017-11-18 11:04:41 DEBUG amqp-relation-changed   File "/var/lib/juju/agents/unit-neutron-api-0/charm/hooks/charmhelpers/contrib/openstack/context.py", line 463, in __call__
2017-11-18 11:04:41 DEBUG amqp-relation-changed     fh.write(b64decode(ctxt['rabbit_ssl_ca']))
2017-11-18 11:04:41 DEBUG amqp-relation-changed TypeError: write() argument must be str, not bytes

### PR DESCRIPTION
**Pull request by ChrisMacNaughton**
Closes #57

### CODE REVIEW

**Comment by ajkavanagh** [comment]
Per conversation, let's get this synced into the charm where the test failed before merging it.  Please note back here when done, and then we can land it.

**Comment by ChrisMacNaughton** [comment]
A mojo run with these changes applied to charm-neutron-api, charm-neutron-gateway, and charm-neutron-openvswitch has just completed successfully

**Comment by tbaumann** [comment]
Sorry guys. That breaks the string comparison.
`if old_cert and old_cert == ca_cert:`

I suppose using open() with 'rb' in retrieve_ca_cert() and using '=' for comparison in above line brings that in line. Use binary all the way.

**Comment by ajkavanagh** [comment]
Hi @tbaumann, re: your comment:

> Sorry guys. That breaks the string comparison.
> `if old_cert and old_cert == ca_cert:`

Please can you expand on this a little?  (i.e. is it breaking a charm somewhere?)  I'm guessing we ought to have gone the other way and stripped `b''` out and used the default strings for each Python version.

If so, I'll raise a bug to that effect.

**Comment by tbaumann** [comment]
Sorry I should have provided more context.
Yes, this broke neutron-api charm.

The current version of the code detects differences in the cert files at every check (update-status every 2min) and re-writes the file.
SSL validations will fail while the file is re-written.

I didn't use the version from charmstore. But as far as i know it is released that way. 
The py3 fixes in neutron-api are from November.
I raised it here because I assume it will affect any charm that uses it.

Easy test
Before
```
2017-12-18 16:17:31 INFO juju-log Installing new CA cert
2017-12-18 16:23:06 INFO juju-log Installing new CA cert
2017-12-18 16:27:51 INFO juju-log Installing new CA cert
2017-12-18 16:33:30 INFO juju-log Installing new CA cert
2017-12-18 16:33:33.318 26551 ERROR oslo_middleware.catch_errors [req-87c8bf03-9966-427e-8b93-bb981a3492ef b8223e
00e8c749989034a62918b66142 03c39f7287da4238aca2bf0b484a93dc - - -] An error occurred during processing the reques
t: GET /v2.0/ports.json?device_id=6927fe06-920d-478c-b4dd-b8983ab2c5e8 HTTP/1.0
2017-12-18 16:37:52 INFO juju-log Installing new CA cert
2017-12-18 16:37:55.183 26543 ERROR oslo_middleware.catch_errors [req-f837ef34-f221-4e07-953a-69b80c886f91 b8223e
00e8c749989034a62918b66142 03c39f7287da4238aca2bf0b484a93dc - - -] An error occurred during processing the reques
t: GET /v2.0/ports.json?tenant_id=c4efa06d235040da8172376d03e0a954&device_id=c66f43bb-32c5-4d80-b2c1-2caf6a545674
 HTTP/1.0
```
after
```
unit-neutron-api-1: 11:24:31 INFO unit.neutron-api/1.juju-log CA cert is the same as installed version
```

old_cert = retrieve_ca_cert(cert_file) reads a normal string
But ca_cert is read in binary mode. (correctly)
old_cert and ca_cert will not be equal even if the string is the same.


This is how I dealt with it. Just read the file in binary mode in retrieve_ca_cert()

```
--- a/hooks/charmhelpers/contrib/hahelpers/apache.py
+++ b/hooks/charmhelpers/contrib/hahelpers/apache.py
@@ -76,7 +76,7 @@ def get_ca_cert():
 def retrieve_ca_cert(cert_file):
     cert = None
     if os.path.isfile(cert_file):
-        with open(cert_file, 'rb') as crt:
+        with open(cert_file, 'r') as crt:
             cert = crt.read()
     return cert
```

**Comment by ajkavanagh** [comment]
Thanks @tbaumann for the explanation; I've raised a bug.

**Pull request merged**
