### PR TITLE
Revert "Set cmd_env for trusty and xenial only (#573)"

### LINKED ISSUE #602: add-apt-repository not using apt https proxy settings
add-apt-repository does not respect the apt https proxy settings in /etc/apt/apt.conf.d/95-juju-proxy-settings
i.e.
```Acquire::https::Proxy "http://10.11.2.10:8000";```

Thus we need to revert back to using ```https_proxy``` environment variable. This behavior was changed in [#573](https://github.com/juju/charm-helpers/pull/573)

```python
    if series in ('trusty', 'xenial'):
        _run_with_retries(['add-apt-repository', '--yes', spec],
                          cmd_env=env_proxy_settings(['https', 'http']))
    else:
        _run_with_retries(['add-apt-repository', '--yes', spec])
```
=> Setting ``` cmd_env=env_proxy_settings(['https', 'http'])``` should be done in all cases.

extra references:
- [LP: #1433761](https://bugs.launchpad.net/ubuntu/+source/software-properties/+bug/1433761)
- https://fabianlee.org/2020/11/16/ubuntu-using-add-apt-repository-with-a-proxy/

### PR DESCRIPTION
**Pull request by coreycb**
This reverts commit 29c9c2c04cff4f4739caa27cd43da3bf80e40646.

Fixes #602

### CODE REVIEW

**Comment by ajkavanagh** [comment]
Doesn't this revert break for the issue raised by #573?  How does that get resolved, or wasn't it a problem in the first place?

**Comment by coreycb** [comment]
Thanks for the link, I hadn't seen the related issue. I'll give that a test.

**Comment by coreycb** [comment]
So I haven't had any luck recreating #573 with the reverted code, but it's very possible I'm missing something.
I cloned and built the cassandra charm. I didn't have any luck picking up my own charm-helpers repo via the wheelhouse.txt so I had to manually update the c-h code on the unit in /var/lib/juju/agents/unit-cassandra-5/.venv/lib/python3.6/site-packages/charmhelpers/fetch/ubuntu.py.

This was also required:
juju model-config apt-http-proxy="http://squid.internal:3128" apt-https-proxy="http://squid.internal:3128"
juju config cassandra install_sources="ppa:cassandra-charmers/stable"

I've reached out to bdmurray to get some advice on how to recreate.

**Comment by murraybd** [comment]
Given that the relevant part of bug 1433761 doesn't in fact seem to be fixed, could we please remove the comment referring to it?

**Review by thedac — APPROVED** [review]
Revert is necessary. Aproved.

**Review by wolsen — APPROVED** [review]
lgtm, we should revert this

**Pull request merged**
