### PR TITLE
fetch.bzrurl: ensure fetched is created when dest is not supplied

### PR DESCRIPTION
**Pull request by axinojolais**

### CODE REVIEW

**Comment by ajkavanagh** [comment]
Hi, @axinojolais the tests will need fixing up for this to be able to be merged.  Also, is there a bug/condition that you hit with this?  Could you update the description to indicate why this change is being made?  Thanks.

**Comment by axinojolais** [comment]
Hi @ajkavanagh yes sorry by PR was a bit impolite :) I'll get to that soon

**Comment by ajkavanagh** [comment]
Hi @axinojolais, do you still wish to continue with this change?  Thanks, Alex.

**Comment by axinojolais** [comment]
Yes, this change still fixes a bug (although on a code path we appear to be the only ones using heh)

**Pull request closed without merging**
