### PR TITLE
Drop Amulet support

### PR DESCRIPTION
**Pull request by AurelienLourot**
Amulet has been replaced by Zaza.

https://launchpad.net/bugs/1828424

### CODE REVIEW

**Comment by AurelienLourot** [comment]
Actually there is urgency to remove this code as it's making use of `distro-info` which makes the new pip resolver clash, see #621

**Comment by ChrisMacNaughton** [comment]
Could we just drop the OpenStack related paths?

**Comment by AurelienLourot** [comment]
`distro_info` is used in `get_ubuntu_releases()`, which isn't OpenStack-related. Or what do you mean?

**Comment by ChrisMacNaughton** [comment]
Is ‘get_ubuntu_releases’ really only used for amulet? That’s quite surprising to me

**Comment by AurelienLourot** [comment]
Yes. Please grep the repo recursively for `get_ubuntu_releases` and you'll see what I'm talking about.

**Comment by ajkavanagh** [comment]
> Actually there is urgency to remove this code as it's making use of `distro-info` which makes the new pip resolver clash, see #621

No I totally agree; let's get rid it of it.

**Comment by fnordahl** [comment]
+1, I was about to merge this but I did not find that the PR removes the offending `distro-info` package from test-requirements.txt?

It is worth noting that while the `distro-info` package has value in the distribution, it is absolutely useless as an independent Python wheel. I guess the best way to consume it across a virtualenv boundary would be to execute the `distro-info` binary.

**Review by fnordahl — DISMISSED** [review]
LGTM, thanks!

**Review by fnordahl — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
