### PR TITLE
Add helper for sequencing charm status checks

### PR DESCRIPTION
**Pull request by przemeklal**
This helper allows to sequence status check functions so that they all
get a chance to run.

Signed-off-by: Przemysław Lal <przemyslaw.lal@canonical.com>

### CODE REVIEW

**Comment by przemeklal** [comment]
This code is already used here: https://github.com/openstack/charm-neutron-gateway/blob/master/hooks/neutron_utils.py#L1161
Now that the same behavior is being reimplemented for charm-neutron-openvswitch, it makes sense to move this code to charm-helpers to avoid duplication.

**Review by coreycb — APPROVED** [review]
LGTM

**Comment by ajkavanagh** [comment]
@przemeklal please could you do a follow-up PR for this that adds tests for this.  I can't decide whether to revert this or ask for a new PR?  Which would you prefer?

**Comment by przemeklal** [comment]
I'll follow up with a new PR.

**Pull request merged**
