### PR TITLE
Escape special chars in nrpe command arguments

### PR DESCRIPTION
**Pull request by mkalcok**
Properly escaping arguments for NRPE checks will prevent possible command injection. It will also remove burden of properly escaping such characters on users part. This need to properly escape special characters is also often not apparent to the user. For example, when currently [configuring queue_thresholds](https://github.com/openstack/charm-rabbitmq-server/blob/bfcc4693b94e671f2287c140ce87190f30afec0b/config.yaml#L114) for rabbitmq-server, if user wants to use wildcards, they must be double-escaped like this:
```
juju config rabbitmq-server queue_threshold="[['\\*', '\\*', 100, 200]]"
```

If charmhelpers would automatically take care of escaping these characters when creating NRPE check commands, the above could be simplified to:
```
juju config rabbitmq-server queue_thresholds="[['*', '*', 100, 200]]"
```

### CODE REVIEW

**Comment by ajkavanagh** [comment]
FYI: I put this up to remove py27 from the lib: #651 -- if/when that lands then this can just be rebased to pick up the changes and it should then check okay.

**Comment by mkalcok** [comment]
@ajkavanagh UTs for this change now pass and it's ready for review.

**Review by ajkavanagh — APPROVED** [review]
LGTM

**Comment by mkalcok** [comment]
thanks

**Pull request merged**
