### PR TITLE
Update restart_on_change to act as a Decorator or context manager

### PR DESCRIPTION
**Pull request by gnuoy**

### CODE REVIEW

**Review by thedac — APPROVED** [review]
I have validated the use of restart_on_change as a context manager in [0]. I also validated no regressions against the keystone charm manually. I have not validated the post and pre restart bits but I assume that Liam has. Code looks good to me.

[0] https://review.opendev.org/c/openstack/charm-mysql-router/+/780992

**Review by ChrisMacNaughton — CHANGES_REQUESTED** [review]
Looks reasonable to me, but the referenced mysql_router change failed in this area:

```
2021-03-16 23:10:24 ERROR juju-log db-router:8: Hook error:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-keystone-mysql-router-0/.venv/lib/python3.8/site-packages/charms/reactive/__init__.py", line 74, in main
    bus.dispatch(restricted=restricted_mode)
  File "/var/lib/juju/agents/unit-keystone-mysql-router-0/.venv/lib/python3.8/site-packages/charms/reactive/bus.py", line 390, in dispatch
    _invoke(other_handlers)
  File "/var/lib/juju/agents/unit-keystone-mysql-router-0/.venv/lib/python3.8/site-packages/charms/reactive/bus.py", line 359, in _invoke
    handler.invoke()
  File "/var/lib/juju/agents/unit-keystone-mysql-router-0/.venv/lib/python3.8/site-packages/charms/reactive/bus.py", line 181, in invoke
    self._action(*args)
  File "/var/lib/juju/agents/unit-keystone-mysql-router-0/charm/reactive/mysql_router_handlers.py", line 102, in proxy_shared_db_responses
    instance.config_changed()
  File "lib/charm/openstack/mysql_router.py", line 645, in config_changed
    with ch_core.host.restart_on_change(
AttributeError: __enter__
```

**Comment by gnuoy** [comment]
> Looks reasonable to me, but the referenced mysql_router change failed in this area:
> 
> ```
> 2021-03-16 23:10:24 ERROR juju-log db-router:8: Hook error:
> Traceback (most recent call last):
>   File "/var/lib/juju/agents/unit-keystone-mysql-router-0/.venv/lib/python3.8/site-packages/charms/reactive/__init__.py", line 74, in main
>     bus.dispatch(restricted=restricted_mode)
>   File "/var/lib/juju/agents/unit-keystone-mysql-router-0/.venv/lib/python3.8/site-packages/charms/reactive/bus.py", line 390, in dispatch
>     _invoke(other_handlers)
>   File "/var/lib/juju/agents/unit-keystone-mysql-router-0/.venv/lib/python3.8/site-packages/charms/reactive/bus.py", line 359, in _invoke
>     handler.invoke()
>   File "/var/lib/juju/agents/unit-keystone-mysql-router-0/.venv/lib/python3.8/site-packages/charms/reactive/bus.py", line 181, in invoke
>     self._action(*args)
>   File "/var/lib/juju/agents/unit-keystone-mysql-router-0/charm/reactive/mysql_router_handlers.py", line 102, in proxy_shared_db_responses
>     instance.config_changed()
>   File "lib/charm/openstack/mysql_router.py", line 645, in config_changed
>     with ch_core.host.restart_on_change(
> AttributeError: __enter__
> ```

I don't think the referenced opendev pr has picked up this change as 'Depends on' doesn't trigger it to be included in the charm build. I have taken the review, added the dependencies and rerun the test: https://paste.ubuntu.com/p/y3r9KDY4k5/

**Review by ChrisMacNaughton — APPROVED** [review]
With the updated test confirmation, this looks great!

**Pull request merged**
