### PR TITLE
[wip] Fixed to handle unicode in charm metadata

### PR DESCRIPTION
**Pull request by hloeung**
Per LP#1721200 [1], charm metadata.yaml may contain unicode characters. We can't open with 'encoding=' because that's Python 3.x only so let's use decode('utf-8') instead.

[1]https://bugs.launchpad.net/bugs/1721200

### CODE REVIEW

**Comment by ajkavanagh** [comment]
Please can we have a test with some UTF-8 (non ASCII) characters in a metadata.yaml that exercises this code?  This is to prevent regressions in the future.  Thanks.

**Comment by hloeung** [comment]
Okay, added a test. I think I have it right, but it's not often I write tests.

**Comment by johnsca** [comment]
The PR description mentions decoding as utf8, but the code decodes as ascii.  Seems like utf8 would be the right choice.

**Comment by ajkavanagh** [comment]
@hloeung @johnsca The `.decode('ascii', 'ignore')` is to just strip any unicode chars that can't be decoded to ascii.  Is that the intention?  If so, I'd rather we had a Py2/Py3 break, in that the PY2 version of the code decodes to 'ascii', and the PY3 version decodes to utf-8 as it uses unicode strings by default, anyway.

Thoughts?

**Comment by hloeung** [comment]
I'll take a look and redo/fix this soon. I'm not sure of how to mark a pull request as "Work in Progress" in GitHub.

**Comment by javacruft** [comment]
Pull request out of date and not actually subject of PR.

**Comment by hloeung** [comment]
Still a WIP, revisiting this after https://github.com/juju/charm-helpers/issues/232

**Pull request closed without merging**
