### PR TITLE
Send unit name alongside ceph requests

### PR DESCRIPTION
**Pull request by gnuoy**
Send the unit name alongside ceph request to support cross model
relations.

### CODE REVIEW

**Review by ChrisMacNaughton — APPROVED** [review]
Given that Ceph [still can't figure out remote unit names](https://github.com/openstack/charm-ceph-mon/blob/8eef7d0c39920402ec84c9b739d29834afdc6e1b/hooks/charmhelpers/core/hookenv.py#L292) after this change, I'm tentatively +1 on landing it, with the additional note that further work will be going into the ceph-mon charm to ensure that CMR is disabled by default

**Comment by johnsca** [comment]
It's worth noting that the reason unit / application names aren't exposed across CMR is that they might conflict with other models. Sending the name of the unit over the relation could lead to the same key being used by applications in different models.  This should really use a unique ID; either a generated UUID (which you'd need to store), or just prepending the `JUJU_MODEL_UUID` to the unit name should work.

**Comment by ChrisMacNaughton** [comment]
This has been fairly heavily discussed within the team. The general conclusion is that the Ceph charms will hard-fail by default when somebody tries to use CMR, and that an option will be added to the Ceph charms to enable "sharing" pools cross-model, which this feature enables. The working assumption with the Ceph charms, in current discussions within the team and with users, is that the cross-models would still be internal things, rather than real trust boundaries.

**Comment by stub42** [comment]
I just noticed that 'juju consume' now allows you to specify the local application name, which will allow the remote application name to use be specified at deployment time, rather than needing to transmit it via the relation.

**Pull request merged**
