### PR TITLE
Don't run 'apt install' when list of packages is empty.

### PR DESCRIPTION
**Pull request by freyes**
A common pattern in charms is to call `apt_install()` passing a filtered
list of packages to avoid reinstallation of packages, so in normal
circumstances a charm may end up calling apt_install() with an empty
list producing the execution of "apt-get install" which will produce at
the very least a read of the list of packages database and build the
dependency tree, this is something that for IO constrained environments
impacts the performance of the running services. Also for environments
where the package database is broken (e.g. a post install script failed)
this would add more entropy and potentially making things more difficult
for the operator to fix.

$ sudo apt-get install
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 63 not upgraded.

### CODE REVIEW

**Comment by ajkavanagh** [comment]
I guess one thought I have around this is which charms might be relying on the 'odd' behaviour to work.  Thus, I'm in favour of landing on master, but would be very reticent to do a backport of this functionality.

**Review by ajkavanagh — APPROVED** [review]
LGTM; would like a second opinion regarding not backporting it as well.

**Comment by freyes** [comment]
On Tue, 2022-08-23 at 02:20 -0700, Alex Kavanagh wrote:
> I guess one thought I have around this is which charms might be relying on the 'odd' behaviour to
> work. Thus, I'm in favour of landing on master, but would be very reticent to do a backport of
> this functionality.

I completely agree with you, I will just let this change organically get into the charms.

Thanks for the review, Alex ;-)

**Comment by freyes** [comment]
@ajkavanagh , the PR got `closed`, hopefully just by mistake :-D

**Comment by ajkavanagh** [comment]
> @ajkavanagh , the PR got `closed`, hopefully just by mistake :-D

Definitely "pushing the wrong button" problem here!  Re-opened and merged.  thanks for the patches!

**Pull request merged**
