### PR TITLE
LP: #1748433 Ansible version changed from 2.0 to 2.5 and there is sev…

### PR DESCRIPTION
**Pull request by fourou**
…eral changes in newer version. The default config of remote_tmp changed from " $HOME/.ansible/tmp" to "~/.ansible/tmp". Also Juju does not expand correctly tild character.

### CODE REVIEW

**Comment by fourou** [comment]
In juju environment we found this issue:

2018-05-17 21:14:31 DEBUG config-changed <localhost> EXEC /bin/sh -c '( umask 77 && mkdi
r -p "` echo ~/.ansible/tmp/ansible-tmp-1526591671.37-231077315121478 `" && echo ansible
-tmp-1526591671.37-231077315121478="` echo ~/.ansible/tmp/ansible-tmp-1526591671.37-2310
77315121478 `" ) && sleep 0'

It seems that it ignore the tild character and according to comment from ansible team: https://github.com/ansible/ansible/issues/21562 comment in Feb 14 by bcoca , he said that it's better to use the 'ansible_remote_tmp' to overrride the configuration variable.

**Comment by fourou** [comment]
For example after deploying the elasticsearch charm wich is based on ansible we found in the charm dir a '~' directory:
root@Elastic:/var/lib/juju/agents/unit-elastic-bionic2-0/charm# ls -l
total 112
-rw-r--r-- 1 root root   410 May 17 19:56  HACKING.md
-rw-r--r-- 1 root root   834 May 17 19:56  Makefile
-rw-r--r-- 1 root root  3010 May 17 19:56  README.md
drwxr-xr-x 2 root root  4096 May 17 19:56  ansible_module_backports
-rw-r--r-- 1 root root   194 May 17 19:56  charm-helpers.yaml
-rw-r--r-- 1 root root  1122 May 17 19:56  config.yaml
-rw-r--r-- 1 root root   756 May 17 19:56  copyright
-rw-r--r-- 1 root root   222 May 17 21:22  elasticsearch-ansible.yml
-rw-r--r-- 1 root root    17 May 17 21:18  elasticsearch.yml
drwxr-xr-x 3 root root  4096 May 17 19:56  hooks
-rw-r--r-- 1 root root 15192 May 17 19:56  icon.svg
-rw-r--r-- 1 root root    54 May 17 19:56  layer.yaml
drwxr-xr-x 2 root root  4096 May 17 19:56  lookup_plugins
-rw-r--r-- 1 root root   611 May 17 19:56  metadata.yaml
-rw-r--r-- 1 root root   240 May 17 21:20  playbook-test.yaml
-rw-r--r-- 1 root root    10 May 17 21:14  playbook.retry
-rw-r--r-- 1 root root  3091 May 17 19:56  playbook.yaml
-rw-r--r-- 1 root root     2 May 17 19:56  revision
drwxr-xr-x 3 root root  4096 May 17 19:28  roles
drwxr-xr-x 2 root root  4096 May 17 19:56  tasks
drwxr-xr-x 2 root root  4096 May 17 19:56  templates
-rw-r--r-- 1 root root   166 May 17 21:21  test.py
drwxr-xr-x 2 root root  4096 May 17 19:56  tests
drwxr-xr-x 2 root root  4096 May 17 19:56  unit_tests
drwx------ 3 root root  4096 May 17 19:33 '~'
root@Elastic:/var/lib/juju/agents/unit-elastic-bionic2-0/charm#

**Comment by fourou** [comment]
Unit test updated.

**Comment by ajkavanagh** [comment]
Thanks for the update.

**Pull request merged**
