### PR TITLE
Add groovy in UBUNTU_RELEASES

### PR DESCRIPTION
**Pull request by pponnuvel**
Signed-off-by: Ponnuvel Palaniyappan <pponnuvel@gmail.com>

### CODE REVIEW

**Review by ajkavanagh — APPROVED** [review]
LGTM

**Comment by ajkavanagh** [comment]
Need an admin with travis CI rebuild perms to re-do the failed build; failed due to snap store timeout.

**Comment by pponnuvel** [comment]
@javacruft might have admin access?

**Comment by ajkavanagh** [comment]
It's a trivial change; I'm just going to bypass it and merge it.

**Pull request merged**
